[package]
name = "openvino"
version = "0.1.0"
authors = ["Andrew Brown <andrew.brown@intel.com>"]
edition = "2018"

[dependencies]
openvino-sys = { path = "../openvino-sys", version = "0.1.0" }
thiserror = "1.0.20"
