[package]
name = "openvino-sys"
version = "0.1.0"
authors = ["Andrew Brown <andrew.brown@intel.com>"]
edition = "2018"
links = "inference_engine_c_api"

[build-dependencies]
bindgen = "0.55.1"
cmake = "0.1.44"

[features]
default = ["cpu"]
all = ["cpu", "gpu", "gna", "hetero", "multi", "myriad"]
cpu = []
gpu = []
gna = []
hetero = []
multi = []
myriad = []
